# pre-installation
- name: Add Rethinkdb repository key
  apt_key:
    url: https://download.rethinkdb.com/repository/raw/pubkey.gpg

# special writing,don't change: In order to solve "apt update error"
- name: Add Rethinkdb repository 
  shell:
    echo "deb [arch=amd64] https://download.rethinkdb.com/repository/ubuntu-{{ansible_distribution_release}} {{ansible_distribution_release}} main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list


- name: Install RethinkDb
  apt:
    name: [rethinkdb]
    update_cache: yes
