# pre-installation
- set_fact:
    ansible_distribution_major_version: "7"
  when: ansible_distribution == "Amazon"

- name: Add Rethinkdb repositories 
  yum_repository:
    name: rethinkdb
    description: rethinkdb repo
    file: rethinkdb
    baseurl: https://download.rethinkdb.com/repository/centos/{{ansible_distribution_major_version}}/x86_64/
    gpgkey: https://download.rethinkdb.com/repository/raw/pubkey.gpg
    gpgcheck: yes
    enabled: yes

- name: Install RethinkDb
  yum:
    name: [rethinkdb]
    update_cache: yes